### ISSUE TITLE
https://www.freecodecamp.org/news/how-to-validate-angular-reactive-forms/

### ISSUE THREAD

**Issue by Vaibhav-143143** [AnkitSharma-007/angular-forms-validation#37]
above link code not work friens

**Comment by AnkitSharma-007** [comment]
Since I wrote that article, there have been some changes in the reactive forms. That is why the code explained in the article may not work for you.

I suggest you refer to the current GitHub repo for the up-to-date code.

**Comment by Vaibhav-143143** [comment]
Thank you for suggestion,
Can i connect with you regarding angular queries if your permission


Thank and regard
Vaibhav solanke
